// <auto-generated />
namespace Medicine_delivery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Edit3OrderMedicineOfPatient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Edit3OrderMedicineOfPatient));
        
        string IMigrationMetadata.Id
        {
            get { return "202301081900377_Edit3OrderMedicineOfPatient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
