// <auto-generated />
namespace Medicine_delivery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EditOrderMedicineofPatient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditOrderMedicineofPatient));
        
        string IMigrationMetadata.Id
        {
            get { return "202301081347439_EditOrderMedicineofPatient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
